title: Morteza Haidari's Portfolio
email: murtaza_haidari2008@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio site showcasing my CV and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-architect
github_username: username

plugins:
  - jekyll-feed
